# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use a recent, stable version
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: '6.1.0' # Use a version compatible with your flake8 settings
    hooks:
    -   id: flake8
        args: [--max-line-length=120, --extend-ignore=E203] # Match .flake8 config if possible
        # You might need to add `additional_dependencies` if flake8 plugins are used
# To add pytest later (can be slow for pre-commit, consider for pre-push or CI):
# -   repo: local
#     hooks:
#       - id: pytest
#         name: pytest
#         entry: pytest
#         language: system # or python if pytest is in requirements.txt
#         types: [python]
#         args: ["--cov=.", "--cov-report=term-missing"]
